---
abstract: 'Format envelope result'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  File::Spec: 0
  IO::Handle: 0
  IPC::Open3: 0
  Test::More: 0.96
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300038, CPAN::Meta::Converter version 2.132510'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Perinci-Result-Format
requires:
  Color::ANSI::Util: 0
  Data::Clean::JSON: 0.11
  Data::Dump::OneLine: 0
  Data::Format::Pretty: 0
  Data::Format::Pretty::Console: 0.12
  Data::Format::Pretty::JSON: 0.03
  Data::Format::Pretty::PHPSerialization: 0
  Data::Format::Pretty::Perl: 0
  Data::Format::Pretty::Ruby: 0
  Data::Format::Pretty::YAML: 0.02
  Rinci: v1.1.38
  Term::Detect::Software: 0
  perl: 5.010001
resources: {}
version: 0.35
